export default {
  target: [
    { name: 'subs', key: 'subs' },
    { name: 'shop', key: 'shop' },
    { name: 'season', key: 'season' },
    { name: 'month', key: 'month' },
    { name: 'valueA', key: 'valueA' },
    { name: 'valueB', key: 'valueB' },
  ],
  source: [
    {
      subs: '上海公司',
      shop: '上海大宁店',
      season: '一季度',
      month: '2022-01',
      valueA: 782,
      valueB: 566,
    },
    {
      subs: '上海公司',
      shop: '上海大宁店',
      season: '一季度',
      month: '2022-02',
      valueA: 856,
      valueB: 403,
    },
    {
      subs: '上海公司',
      shop: '上海大宁店',
      season: '一季度',
      month: '2022-03',
      valueA: 886,
      valueB: 555,
    },
    {
      subs: '上海公司',
      shop: '上海大宁店',
      season: '二季度',
      month: '2022-04',
      valueA: 555,
      valueB: 444,
    },
    {
      subs: '上海公司',
      shop: '上海大宁店',
      season: '二季度',
      month: '2022-05',
      valueA: 444,
      valueB: 333,
    },
    {
      subs: '上海公司',
      shop: '上海曹家渡店',
      season: '一季度',
      month: '2022-01',
      valueA: 922,
      valueB: 778,
    },
    {
      subs: '上海公司',
      shop: '上海曹家渡店',
      season: '一季度',
      month: '2022-02',
      valueA: 888,
      valueB: 887,
    },
    {
      subs: '上海公司',
      shop: '上海曹家渡店',
      season: '一季度',
      month: '2022-03',
      valueA: 879,
      valueB: 870,
    },
    {
      subs: '上海公司',
      shop: '上海曹家渡店',
      season: '二季度',
      month: '2022-04',
      valueA: 800,
      valueB: 723,
    },
    {
      subs: '上海公司',
      shop: '上海曹家渡店',
      season: '二季度',
      month: '2022-05',
      valueA: 813,
      valueB: 789,
    },
    {
      subs: '浙江公司',
      shop: '浙江总店',
      season: '一季度',
      month: '2022-01',
      valueA: 500,
      valueB: 463,
    },
    {
      subs: '浙江公司',
      shop: '浙江总店',
      season: '一季度',
      month: '2022-02',
      valueA: 833,
      valueB: 456,
    },
    {
      subs: '浙江公司',
      shop: '浙江总店',
      season: '一季度',
      month: '2022-03',
      valueA: 821,
      valueB: 442,
    },
    {
      subs: '浙江公司',
      shop: '浙江总店',
      season: '二季度',
      month: '2022-04',
      valueA: 834,
      valueB: 456,
    },
    {
      subs: '浙江公司',
      shop: '浙江总店',
      season: '二季度',
      month: '2022-05',
      valueA: 803,
      valueB: 700,
    },
  ],
};
