# 系统的 appCode 唯一标示
appCode: rocket-chart-gallery

# 系统的标题
pageTitle: rocket-chart-gallery

# api前缀
# 为了支持透传功能，区分 ajax 请求和正常页面访问，如
# 页面访问 /xxx/userGroup
# 接口请求 /xxx/api/userGroup/query
# 由于是单页应用，使用 HTML5 history 模式，需要对页面请求使用 主页 渲染
apiPrefix: /api

# 基础路径
# 目前大量的系统是挂载在同一个域名下，使用不同的路径做区别
baseURI: '/rocket-chart-gallery'

# 链接访问白名单
# 在鉴权中间件中会将以下地址添加到白名单
authWhiteList: ['/download']

# 后端 Java 服务接口地址
backendMap:
  dev: http://localhost:8080/rocket-chart-gallery
  test: http://192.168.60.38:9002
  uat: http://192.168.60.38:9002
  prod: http://cms.9nali.com/rocket-chart-gallery

server:
  port: 8080
  devPort: 9005
  debugPort: 7005

# cas登录链接
casUrl:
  dev: http://localhost:8080/rocket-chart-gallery
  test: http://test.ximalaya.com/rocket-chart-gallery
  uat: http://
  prod: http://

# 服务地址
routeMap:
  dev: http://localhost:8080/rocket-chart-gallery
  test: http://test.ximalaya.com/rocket-chart-gallery
  uat: http://ops.uat.ximalaya.com/rocket-chart-gallery
  prod: http://ops.ximalaya.com/rocket-chart-gallery
